import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import { useState } from "react"


// Awesome Reveal
import Reveal from "react-awesome-reveal";
import { keyframes } from "@emotion/react";

import HeaderSecond from '../../../components/HeaderSecond'
import Footer from "../../../components/Footer"

import { PortfolioData } from "../../../datas/Portfolio/PortfolioData"


// Keyframe for smooth reveal
const revealTop = keyframes`
  from {
    opacity: 0;
    transform: translateY(-30px);
  }

  to {
    opacity: 1;
    transform: translateY(0);
  }
`;



export default function TwoColumnsPortfolio() {
    const [loadMore, setLoadMore] = useState(6);
    const [loading, setLoading] = useState(false);
    const [categorieFilter, setCategorieFilter] = useState("all");

    function loadMoreArticle() {
        setLoading(true);
        setTimeout(() => {
            setLoadMore(loadMore + 2);
            setLoading(false);
        }, 1500)
    };

    function changeActivefilter(categorieSelection) {
        let target = document.getElementById(categorieSelection);
        let remove = document.querySelector('.filterPortfolioActive');
        remove.classList.remove('filterPortfolioActive');
        target.classList.add('filterPortfolioActive');
    }   

    function changeCategorie(categorieSelection) {
        setCategorieFilter(categorieSelection);
    }
    
    function filterCategorie(categorieSelection) {
        changeActivefilter(categorieSelection);
        changeCategorie(categorieSelection);
    }


    return(
        <div class='font-NunitoSans'>
            <Head>
                <title>ZikZag | 2 Columns Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../"/>
            </Head>

            <HeaderSecond />

            <main>
                <section className="bg-singlePortfolioStandardBackground bg-cover bg-no-repeat text-center text-white">
                    <h1 className="font-Amiri text-6xl pt-60 mb-6">Portfolio 2 Col</h1>
                    <p className="font-semibold text-sm pb-48 z-10"><span className="opacity-50">HOME &gt; </span> PORTFOLIO 2 COL</p>
                </section>

                <div className='w-[62%] min-w-[1180px] m-auto text-center mb-40 max-xl:w-[90%] max-xl:min-w-fit'>
                    <h2 className='text-orange font-semibold relative mb-2 mt-20 w-52 m-auto'><span className='absolute bottom-1 left-3 bg-orange h-0.5 w-2'></span>BUSINESS PORTFOLIO<span className='absolute bottom-1 ml-1 bg-orange h-0.5 w-2'></span></h2>
                    <h3 className='text-slightGrey text-5xl font-Amiri leading-tight mb-3'>Our Case Studies</h3>
                    <p className='text-greyText text-lg w-7/12 m-auto'>We are specialists in both economics and information technologies and we apply our full range of talent to creating the perfect solution for each client’s needs.</p>


                    <div className='flex justify-between mt-14 w-2/3 m-auto 850:flex-col 850:items-center 850:w-full'>
                        <button onClick={() => filterCategorie('all')} id='all' className="font-bold text-sm py-1 px-3.5 filterPortfolioActive 850:mb-3">ALL WORKS</button>
                        <button onClick={() => filterCategorie('corporate')} id='corporate' className="font-bold text-sm py-1 px-3.5 850:mb-3">CORPORATE</button>
                        <button onClick={() => filterCategorie('finance')} id='finance' className="font-bold text-sm py-1 px-3.5 850:mb-3">FINANCE</button>
                        <button onClick={() => filterCategorie('marketing')} id='marketing' className="font-bold text-sm py-1 px-3.5 850:mb-3">MARKETING</button>
                        <button onClick={() => filterCategorie('startup')} id='startup' className="font-bold text-sm py-1 px-3.5 850:mb-3">STARTUP</button>
                        <button onClick={() => filterCategorie('strategy')} id='strategy' className="font-bold text-sm py-1 px-3.5 850:mb-3">STRATEGY</button>
                    </div>


                    <div className='min-w-[1180px] m-auto gap-7 mt-10 grid grid-cols-2 max-xl:grid-cols-1 max-xl:min-w-fit'>
                        {PortfolioData.slice(0, loadMore).map((el) => {
                            if(el.categorie.includes(categorieFilter)) {
                                return(
                                    <Reveal key={el.index} keyframes={revealTop} duration={600} delay={el.delay} triggerOnce className="relative">
                                    <Link href='/Portfolio/Single'>
                                    <div className='group relative'>
                                        <Image src={el.background} alt="photo d'entreprise" className='rounded-xl max-xl:m-auto max-xl:w-[90%]' />
                                        <div className='text-center bg-white rounded-lg absolute -bottom-2 left-[50%] translate-x-[-50%] py-5 w-[90%] shadow-[6px_5px_16px_0px_rgb(0,0,0,0.15)] -translate-y-10 opacity-0 group-hover:translate-y-0 group-hover:opacity-100 ease-in-out duration-500'>
                                            <p className='font-Amiri text-slightGrey text-3xl leading-[32px] mb-2 hover:text-orange ease-in-out duration-300'>{el.title}</p>
                                            <p className='text-orange font-semibold text-sm'>{el.line}</p>
                                        </div>
                                    </div>
                                    </Link>
                                    </Reveal>
                                )
                            }
                        })}
                    </div>  

                    {loadMore < PortfolioData.length 
                        && <button onClick={loadMoreArticle} className='mt-10 text-sm text-slightGrey font-bold w-[170px] m-auto py-5 border border-orange rounded border-solid hover:bg-orange hover:border-transparent hover:text-white ease-in-out duration-300'>{loading === false ? 'LOAD MORE' : <div class="spinnerArticle"></div>}</button>
                    }
                </div>
            </main>

            <Footer />
        </div>
    )
}