import Head from 'next/head'
import Image from 'next/image'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTwitter, faFacebookF, faPinterestP, faInstagram } from '@fortawesome/free-brands-svg-icons'

import logo from '../../public/assets/PAGES/ComingSoon/logo.png'

export default function About() {
    return (
        <div className='font-NunitoSans'>
            <Head>
                <title>ZikZag | ComingSoon</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../"/>
            </Head>

            <main className='bg-comingTeamBackground bg-center bg-no-repeat text-center'>
                <Image src={logo} alt="logo de l'entreprise" className='pt-14 pb-24 ml-auto mr-auto' />
                <h1 className='font-Amiri text-white text-[80px]'>We`re Coming Soon</h1>

                <div className='flex justify-center items-center text-white font-Amiri text-[120px] mt-4'>
                    <div>
                        <p>47</p>
                        <p className='font-NunitoSans text-lg font-bold relative -top-8'>DAYS</p>
                    </div>
                    
                    <span className='mx-20 text-orange font-NunitoSans text-8xl relative bottom-6'>:</span>

                    <div>
                        <p>05</p>
                        <p className='font-NunitoSans text-lg font-bold relative -top-8'>HOURS</p>
                    </div>
                    
                    <span className='mx-20 text-orange font-NunitoSans text-8xl relative bottom-6'>:</span>

                    <div>
                        <p>25</p>
                        <p className='font-NunitoSans text-lg font-bold relative -top-8'>MINUTES</p>
                    </div>
                    
                    <span className='mx-20 text-orange font-NunitoSans text-8xl relative bottom-6'>:</span>

                    <div>
                        <p>32</p>
                        <p className='font-NunitoSans text-lg font-bold relative -top-8'>SECONDS</p>
                    </div>
                </div>

                <p className='text-white text-lg leading-8 mt-8'>We are working very hard on the new version of our site.<br></br>It will bring a lot of new features. Stay tuned!</p>
            
                <div className='mt-8 pb-28'>
                    <input type='email' placeholder='Your Email *' className='bg-[#f5f5f533] placeholder:text-white p-3.5 rounded-sm w-96 mr-5'></input>
                    <button className='text-white font-bold text-sm bg-orange px-8 py-4 rounded'>SUBSCRIBE</button>
                </div>

                <div className='flex justify-center items-center pb-[63px]'>
                    <div className='bg-[#1DA1F2] p-[9px] rounded-full mb-3 mr-3 hover:shadow-none hover:bg-white ease-in-out duration-300 group'><FontAwesomeIcon icon={faTwitter} className='w-3.5 text-white group-hover:text-[#1DA1F2]' /></div>
                    <div className='bg-[#3B5998] px-3 py-2.5 rounded-full mb-3 mr-3 hover:shadow-none hover:bg-white ease-in-out duration-300 group'><FontAwesomeIcon icon={faFacebookF} className='w-2 text-white group-hover:text-[#3B5998]' /></div>
                    <div className='bg-[#E40000] px-3 py-2.5 rounded-full mb-3 mr-3 hover:shadow-none hover:bg-white ease-in-out duration-300 group'><FontAwesomeIcon icon={faPinterestP} className='w-2.5 text-white group-hover:text-[#E40000]' /></div>
                    <div className='bg-[#C32AA3] p-2 rounded-full mb-3 mr-3 hover:shadow-none hover:bg-white ease-in-out duration-300 group'><FontAwesomeIcon icon={faInstagram} className='w-3.5 text-white group-hover:text-[#C32AA3]' /></div>
                </div>
            </main>
        </div>  
    )
}