import Head from 'next/head'

import HeaderSecond from '../../components/HeaderSecond'
import Footer from '../../components/Footer'
import AccordionsElement from '../../components/PAGES/Elements/01Accordions'
import InfoElement from '../../components/PAGES/Elements/02Info'
import ProgressElement from '../../components/PAGES/Elements/03Progress'
import FlipElement from '../../components/PAGES/Elements/04Flip'
import PricingElement from '../../components/PAGES/Elements/05Pricing'
import CounterElement from '../../components/PAGES/Elements/06Counter'
import PartnersElement from '../../components/PAGES/Elements/07Partners'
import TestimonialElement from '../../components/PAGES/Elements/08Testimonial'
import ButtonsElement from '../../components/PAGES/Elements/09Buttons'


export default function About() {
    return (
        <div className='font-NunitoSans'>
            <Head>
                <title>ZikZag | Elements</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../"/>
            </Head>

            <HeaderSecond />

            <main>
                <section className="bg-elementsTeamBackground bg-no-repeat text-center text-white">
                    <h1 className="font-Amiri text-6xl pt-60 mb-6">Elements</h1>
                    <p className="font-semibold text-sm pb-48 z-10"><span className="opacity-50">HOME &gt;</span> ELEMENTS</p>
                </section>

                <div className='mx-[20%] mb-40'>
                    <AccordionsElement />

                    <InfoElement />

                    <ProgressElement />

                    <FlipElement />

                    <PricingElement />

                    <CounterElement />

                    <PartnersElement />

                    <TestimonialElement />

                    <ButtonsElement />
                </div>
            </main>

            <Footer />
        </div>  
    )
}