import Head from 'next/head'
import { useState } from 'react'

import HeaderSecond from '../../components/HeaderSecond'
import Footer from '../../components/Footer'
import WidgetTheme from '../../components/WidgetTheme'

import AccordionsElement from '../../components/PAGES/Elements/01Accordions'
import InfoElement from '../../components/PAGES/Elements/02Info'
import ProgressElement from '../../components/PAGES/Elements/03Progress'
import FlipElement from '../../components/PAGES/Elements/04Flip'
import PricingElement from '../../components/PAGES/Elements/05Pricing'
import CounterElement from '../../components/PAGES/Elements/06Counter'
import PartnersElement from '../../components/PAGES/Elements/07Partners'
import TestimonialElement from '../../components/PAGES/Elements/08Testimonial'
import ButtonsElement from '../../components/PAGES/Elements/09Buttons'


export default function About() {
    const [faqResponse, setFaqResponse] = useState(null);

    function activeResponse(responseTarget) {
        let target = document.getElementById(responseTarget);
        let remove = document.getElementsByClassName('faqResponseActive');
        if(remove.length === 0) {
            target.classList.add('faqResponseActive');
            target.classList.add('mb-32');
        } else if(faqResponse === responseTarget) {
            remove[0].classList.remove('faqResponseActive', 'mb-32');
        } else {
            remove[0].classList.remove('faqResponseActive', 'mb-32');
            target.classList.add('faqResponseActive');
            target.classList.add('mb-32');
        }
    }


    return (
        <div className='font-NunitoSans'>
            <Head>
                <title>ZikZag | Elements</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../"/>
            </Head>

            <HeaderSecond />

            <main className='relative z-10'>
                <section className="bg-elementsTeamBackground bg-cover bg-no-repeat text-center text-white">
                    <h1 className="font-Amiri text-6xl pt-60 mb-6">Elements</h1>
                    <p className="font-semibold text-sm pb-48 z-10"><span className="opacity-50">HOME &gt;</span> ELEMENTS</p>
                </section>

                <div>
                    <div className='w-[60%] min-w-[1150px] m-auto max-xl:w-[85%] max-xl:min-w-fit'>
                        <AccordionsElement />

                        <InfoElement />

                        <ProgressElement />

                        <FlipElement />

                        <PricingElement />

                        <CounterElement />
                    </div>

                    <PartnersElement />

                    <TestimonialElement />

                    <div className='w-[60%] min-w-[1150px] m-auto mb-40 max-xl:w-[85%] max-xl:min-w-fit'>
                        <ButtonsElement />
                    </div>
                </div>
            </main>

            <WidgetTheme />

            <Footer />
        </div>  
    )
}