import Head from "next/head"

import HeaderSecond from '../../components/HeaderSecond'
import Footer from "../../components/Footer"
import WidgetTheme from '../../components/WidgetTheme'

import PresentationSingle from "../../components/PAGES/Single/01Presentation"
import TextSingle from "../../components/PAGES/Single/02Text"
import ContactSingle from "../../components/PAGES/Single/03Contact"


export default function SingleTeam() {
    return(
        <div class='font-NunitoSans'>
            <Head>
                <title>ZikZag | SingleTeam</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../"/>
            </Head>

            <HeaderSecond />

            <main className='relative z-10'>
                <section className="bg-singleTeamBackground bg-no-repeat bg-cover text-center text-white">
                    <h1 className="font-Amiri text-6xl pt-60 mb-6">Team</h1>
                    <p className="font-semibold text-sm pb-48 z-10"><span className="opacity-50">HOME &gt; TEAM &gt;</span> MARRY CLARINS</p>
                </section>

                <PresentationSingle />

                <TextSingle />

                <ContactSingle />
            </main>

            <WidgetTheme />

            <Footer />
        </div>
    )
}