import Head from "next/head"
import Image from "next/image"

import HeaderSecond from '../../components/HeaderSecond'
import Footer from "../../components/Footer"

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faXmark } from "@fortawesome/free-solid-svg-icons"

import item from '../../public/assets/SHOP/item_1.jpg'


export default function Cart() {
    return(
        <div className='font-NunitoSans'>
             <Head>
                <title>ZikZag | Cart</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../"/>
            </Head>

            <HeaderSecond />

            <main>
                <section className="bg-singleLayoutsStandardBackground bg-cover bg-no-repeat text-center text-white">
                    <h1 className="font-Amiri text-6xl pt-60 mb-6">Cart</h1>
                    <p className="font-semibold text-sm pb-48 z-10"><span className="opacity-50">HOME &gt; </span> CART</p>
                </section>


                {7 == 7 
                ?   <section className='mt-20 mb-40 mx-[19%]'>
                        <div className='flex font-bold text-white text-lg bg-darkBlueBackground py-5 rounded'>
                            <p className='ml-8 mr-96'>Product</p>
                            <p className='mr-40'>Price</p>
                            <p className='mr-auto'>Quantity</p>
                            <p className='mr-32'>Total</p>
                        </div>

                        <div className='flex items-center mt-8'>
                            <Image src={item} alt='photo de produit' className='w-20' />
                            <p className='font-Amiri text-slightGrey pl-12 mr-2'>Flying Ninja</p>
                            <p className='font-bold text-lg pl-64'>$12.00</p>
                            <input type='number' value={1} min={1} max={9} className='font-bold ml-36 pl-4 bg-greyBackground' />
                            <p className='font-bold text-lg pl-64 ml-2'>$12.00</p>
                            <FontAwesomeIcon icon={faXmark} className='w-3 ml-20 text-[#c9c7c4] hover:text-orange ease-in-out durattion-300 hover:cursor-pointer' />
                        </div>

                        <span className='mt-8 h-px w-[62%] bg-[#e4e4e4] absolute'></span>
                        
                        <div className='mt-16'>
                            <input type='text' placeholder='Coupon code' className='bg-greyBackground rounded py-3.5 pl-4 placeholder:text-greyText mr-3' />
                            <button className="text-white font-bold text-sm bg-darkBlueBackground rounded py-4 px-7 mr-[54.5%] hover:bg-orange ease-in-out duration-300">APPLY COUPON</button>
                            <button className="text-white font-bold text-sm bg-orange rounded py-4 px-7">UPDATE CART</button>
                        </div>

                        <div className='mt-16 rounded border border-solid border-[#e4e4e4] w-[30%] ml-auto p-8'>
                            <p className='font-Amiri text-2xl mb-6'>Cart Totals</p>
                            <span className='h-px w-[15%] bg-[#e4e4e4] absolute'></span>
                            <div className='mt-12 flex justify-between mb-6'>
                                <p className='font-Amiri text-lg'>Subtotal</p>
                                <p className='text-lg font-semibold'>$12.00</p>
                            </div>
                            <span className='h-px w-[15%] bg-[#e4e4e4] absolute'></span>
                            <div className='mt-12 flex justify-between mb-8'>
                                <p className='font-Amiri text-lg'>Total</p>
                                <p className='font-bold text-[20px]'>$12.00</p>
                            </div>
                            <button className='bg-orange w-full rounded py-3.5 text-white font-bold hover:bg-darkBlueBackground ease-in-out duration-300'>PROCEED TO CHECKOUT</button>
                        </div>
                    </section>
            
                :   <section className='pt-24 mb-80 flex ml-96 items-center'>
                        <p className='text-lg text-greyText mr-10 font-NunitoSans'>Your cart is currently empty.</p>
                        <button className="bg-darkBlueBackground font-semibold text-sm text-white rounded py-3.5 px-7">RETURN TO SHOP</button>
                    </section>
                }
            </main>

            <Footer />
        </div>
    )
}