import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import { useEffect, useState } from "react"

import HeaderSecond from '../../components/HeaderSecond'
import Footer from "../../components/Footer"

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faXmark } from "@fortawesome/free-solid-svg-icons"


export default function Cart() {
    const [item, setItem] = useState([]);
    const [cost, setCost] = useState(0)

    useEffect(() => {
        const itemData = sessionStorage.getItem('itemData');
        const item = JSON.parse(itemData);
        setItem(item);

        if(item) {
            let totalPrice = 0;
            item.forEach(item => {
                const price = item.price.split('$');
                const numberPrice = parseInt(price[1]);
                setCost(totalPrice += numberPrice)
            });
        }
    }, [])

    function removeItem(index) {
        let storageData = sessionStorage.getItem('itemData');
        let data = JSON.parse(storageData);

        data.splice(index, 1);

        sessionStorage.setItem('itemData', JSON.stringify(data));
        location.reload();
    }


    // function that handle incr and decr for input number
    function inc(element) {
        let el = document.getElementById(element);
        el.value = parseInt(el.value) + 1;
    }
      
    function dec(element) {
      let el = document.getElementById(element);
        if (parseInt(el.value) > 0) {
          el.value = parseInt(el.value) - 1;
      }
    }


    return(
        <div className='font-NunitoSans'>
             <Head>
                <title>ZikZag | Cart</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../"/>
            </Head>

            <HeaderSecond />

            <main>
                <section className="bg-singleLayoutsStandardBackground bg-cover bg-no-repeat text-center text-white">
                    <h1 className="font-Amiri text-6xl pt-60 mb-6">Cart</h1>
                    <p className="font-semibold text-sm pb-48 z-10"><span className="opacity-50">HOME &gt; </span> CART</p>
                </section>


                {item.length != 0
                ?   <section className='mt-20 mb-40 w-[62%] m-auto min-w-[1180px] 1050-xl:min-w-[1000px] relative 850-1050:min-w-[820px] 850:min-w-fit 850:w-[90%]'>
                        <div className='850:flex 850:justify-between'>
                            <div className='flex font-bold text-white text-lg bg-darkBlueBackground py-5 rounded 650 850:flex-col 850:bg-white 850:text-slightGrey'>
                                <p className='ml-[3%] 850:ml-0 850:mb-7'>Product</p>
                                <p className='ml-[32%] 1050-xl:ml-[28%] 850-1050:ml-[24%] 850:ml-0 850:mb-7'>Price</p>
                                <p className='ml-[14%] 850:ml-0 850:mb-9'>Quantity</p>
                                <p className='ml-[21.5%] 1050-xl:ml-[18%] 850-1050:ml-[14%] 850:ml-0 850:mb-7'>Total</p>
                            </div>

                            {item.map((el, index) => {
                                return(
                                    <div key={index} className='flex items-center mt-8 850:flex-col 850:items-end 850:mt-4'>
                                        <Image src={el.picture} alt='photo de produit' className='w-20 ml-[1.5%] 850:hidden' />
                                        <p className='font-Amiri text-slightGrey pl-8 850:pl-0 850:mb-7'>{el.name}</p>
                                        <p className='font-bold text-lg ml-[22%] 1050-xl:ml-[17%] 850-1050:ml-[13%] 850:ml-0 850:mb-7'>{el.price}</p>

                                        <div class='relative quantity flex ml-[13%] 850-1050:ml-[10%] 850:ml-0 850:mb-7'>
                                            <input name='number' id='number' type='number' defaultValue={1} step={1} placeholder='1' inputMode='numeric' min={1} max={9} className='bg-greyBackground font-bold pl-4 rounded outline-none' />
                                            <div className='flex flex-col'>
                                                <button onClick={() => inc('number')} className='bg-greyBackground font-bold text-lg h-[26px] w-[36px]'>+</button>
                                                <button onClick={() => dec('number')} className='bg-greyBackground font-bold text-lg h-[26px] w-[36px]'>-</button>
                                            </div>
                                        </div>

                                        <p className='font-bold text-lg pl-[20%] 1050-xl:pl-[15%] 850-1050:pl-[10%] ml-2 850:ml-0 850:mb-7'>{el.price}</p>
                                        <FontAwesomeIcon onClick={() => removeItem(index)} icon={faXmark} className='w-3 ml-20 text-[#c9c7c4] hover:text-orange ease-in-out duration-300 hover:cursor-pointer' />
                                    </div>
                                )
                            })}
                        </div>
                        

                        <span className='mt-8 h-px w-full bg-[#e4e4e4] absolute'></span>
                        
                        <div className='mt-16 flex 850:flex-col'>
                            <input type='text' placeholder='Coupon code' className='bg-greyBackground rounded py-3.5 pl-4 placeholder:text-greyText mr-3' />
                            <button className="text-white font-bold text-sm bg-darkBlueBackground mr-auto rounded py-4 px-7 hover:bg-orange ease-in-out duration-300 850:my-4">APPLY COUPON</button>
                            <button className="text-white font-bold text-sm bg-orange rounded py-4 px-7">UPDATE CART</button>
                        </div>

                        <div className='mt-16 rounded border border-solid border-[#e4e4e4] w-[30%] ml-auto p-8 850:w-[95%] 850:mr-auto'>
                            <p className='font-Amiri text-2xl mb-6'>Cart Totals</p>
                            <span className='h-px w-[15%] bg-[#e4e4e4] absolute'></span>
                            <div className='mt-12 flex justify-between mb-6'>
                                <p className='font-Amiri text-lg'>Subtotal</p>
                                <p className='text-lg font-semibold'>${cost}.00</p>
                            </div>
                            <span className='h-px w-[15%] bg-[#e4e4e4] absolute'></span>
                            <div className='mt-12 flex justify-between mb-8'>
                                <p className='font-Amiri text-lg'>Total</p>
                                <p className='font-bold text-[20px]'>${cost}.00</p>
                            </div>
                            <button className='bg-orange w-full rounded py-3.5 text-white font-bold hover:bg-darkBlueBackground ease-in-out duration-300'>PROCEED TO CHECKOUT</button>
                        </div>
                    </section>
            
                :   <section className='pt-24 mb-80 flex ml-[15%] items-center 650:mx-[5%]'>
                        <p className='text-lg text-greyText mr-10 font-NunitoSans'>Your cart is currently empty.</p>
                        <Link href='/Shop/Shop/Page1'><button className="bg-darkBlueBackground font-semibold text-sm text-white rounded py-3.5 px-7 hover:bg-orange ease-in-out duration-300">RETURN TO SHOP</button></Link>
                    </section>
                }
            </main>

            <Footer />
        </div>
    )
}