import Head from "next/head"
import Link from "next/link"
import { useEffect, useState } from "react"

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faCircleInfo, faXmark } from "@fortawesome/free-solid-svg-icons"

import HeaderSecond from '../../components/HeaderSecond'
import Footer from "../../components/Footer"


export default function Checkout() {
    const [item, setItem] = useState([]);
    const [cost, setCost] = useState(0)

    useEffect(() => {
        const itemData = sessionStorage.getItem('itemData');
        const item = JSON.parse(itemData);
        setItem(item);

        if(item) {
            let totalPrice = 0;
            item.forEach(item => {
                const price = item.price.split('$');
                const numberPrice = parseInt(price[1]);
                setCost(totalPrice += numberPrice)
            });
        }
    }, [])


    return(
        <div className='font-NunitoSans'>
            <Head>
                <title>ZikZag | Checkout</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../"/>
            </Head>

            <HeaderSecond />

            <main>
                <section className="bg-singleLayoutsStandardBackground bg-cover bg-no-repeat text-center text-white">
                    <h1 className="font-Amiri text-6xl pt-60 mb-6">Checkout</h1>
                    <p className="font-semibold pb-48 z-10"><span className="opacity-50">HOME &gt; </span> CHECKOUT</p>
                </section>

                {item.length != 0
                ?   <div className='mt-20 mb-40 w-[62%] m-auto min-w-[1050px] max-xl:min-w-fit'>
                        <div className='flex items-center bg-white p-2 shadow-[6px_5px_30px_0px_rgb(0,0,0,0.12)] rounded'>
                            <div className='p-2.5 rounded bg-[#179fff]'><FontAwesomeIcon icon={faCircleInfo} className='w-9 text-white' /></div>
                            <p className='text-sm font-light ml-5'>Have a coupon? <span className='text-orange ml-2'>Click here to enter your code</span></p>
                            <FontAwesomeIcon icon={faXmark} className='w-3 text-[#e5e5e5] ml-auto mr-4' />
                        </div>

                        <div className='flex justify-between mt-8 max-xl:flex-col max-xl:items-center'>
                            <div className='w-[47%] 650-xl:w-[70%] max-xl:mb-24 650:w-[90%]'>
                                <h2 className='font-Amiri text-slightGrey text-4xl'>Billing Details</h2>

                                <form className='mt-6'>
                                    <div className='flex justify-between 650:flex-col'>
                                        <div className='flex flex-col w-[48%] 650:w-full'>
                                            <label htmlfor='firstName' className='text-slightGrey font-bold mb-2'>First Name*</label>
                                            <input name='firstName' type='text' className='bg-greyBackground rounded py-4 px-5 outline-none' />
                                        </div>

                                        <div className='flex flex-col w-[48%] 650:w-full'>
                                            <label htmlfor='lastName' className='text-slightGrey font-bold mb-2'>Last Name*</label>
                                            <input name='lastName' type='text' className='bg-greyBackground rounded py-4 px-5 outline-none' />
                                        </div>
                                    </div>
                                        
                                    <div className='flex flex-col w-full mt-5'>
                                        <label htmlfor='compagny' className='text-slightGrey font-bold mb-2'>Compagny Name (optional)</label>
                                        <input name='compagny' type='text' className='bg-greyBackground rounded py-4 px-5 outline-none' />
                                    </div>

                                    <div className='flex flex-col w-full mt-5'>
                                        <label htmlfor='country' className='text-slightGrey font-bold mb-2'>Country / Region *</label>
                                        <input name='country' type='text' className='bg-greyBackground rounded py-4 px-5 outline-none' />
                                    </div>

                                    <div className='flex flex-col w-full mt-5'>
                                        <label htmlfor='adress' className='text-slightGrey font-bold mb-2'>Street address *</label>
                                        <input name='adress' type='text' placeholder='House number and street name' className=' mb-2 bg-greyBackground rounded py-4 px-5 outline-none text-greyText' />
                                        <input name='adress' type='text' placeholder='Apartment, suite, unit, etc. (optional)' className='bg-greyBackground rounded py-4 px-5 outline-none' />
                                    </div>

                                    <div className='flex flex-col w-full mt-5'>
                                        <label htmlfor='town' className='text-slightGrey font-bold mb-2'>Town / City *</label>
                                        <input name='town' type='text' className='bg-greyBackground rounded py-4 px-5 outline-none' />
                                    </div>

                                    <div className='flex flex-col w-full mt-5'>
                                        <label htmlfor='county' className='text-slightGrey font-bold mb-2'>County (optional)</label>
                                        <input name='county' type='text' className='bg-greyBackground rounded py-4 px-5 outline-none' />
                                    </div>

                                    <div className='flex flex-col w-full mt-5'>
                                        <label htmlfor='postcode' className='text-slightGrey font-bold mb-2'>Postcode *</label>
                                        <input name='postcode' type='text' className='bg-greyBackground rounded py-4 px-5 outline-none' />
                                    </div>

                                    <div className='flex flex-col w-full mt-5'>
                                        <label htmlfor='phone' className='text-slightGrey font-bold mb-2'>Phone *</label>
                                        <input name='phone' type='text' className='bg-greyBackground rounded py-4 px-5 outline-none' />
                                    </div>

                                    <div className='flex flex-col w-full mt-5'>
                                        <label htmlfor='email' className='text-slightGrey font-bold mb-2'>Email address *</label>
                                        <input name='email' type='text' className='bg-greyBackground rounded py-4 px-5 outline-none' />
                                    </div>
                                </form>

                                <h2 className='font-Amiri text-slightGrey text-4xl mt-6 mb-3'>Additional information</h2>
                                <div className='flex flex-col'>
                                    <label htmlfor='notes' className='text-slightGrey font-bold mb-2'>Order notes (optional)</label>
                                    <textarea name='notes' placeholder='Notes about your order, e.g. special notes for delivery.'className='rounded bg-greyBackground px-5 py-4 h-28' />
                                </div>
                            </div>



                            <div className='w-[47%] relative 650-xl:w-[70%] 650:w-[90%]'>
                                <h2 className='font-Amiri text-slightGrey text-4xl mb-6'>Your order</h2>

                                <div className='rounded bg-darkBlueBackground flex items-center justify-between pl-10 pr-24 py-4 text-lg text-white font-bold 430:pr-10'>
                                    <p>Product</p>
                                    <p>Subtotal</p>
                                </div>

                                {item.map((el, index) => {
                                    return(
                                        <div key={index} className='flex items-center justify-between pl-10 pr-24 py-4 text-lg mt-4 430:pr-10'>
                                            <p className='font-Amiri text-[17px]'>{el.name} <span className='text-[#e5e5e5]'>x 1</span></p>
                                            <p className='font-bold'>{el.price}</p>
                                        </div>
                                    )
                                })}

                                <span className='h-px bg-[#e5e5e5] w-full absolute mt-6'></span>

                                <div className='flex items-center justify-between pl-10 pr-24 py-4 text-lg mt-6 430:pr-10'>
                                    <p className='font-extrabold'>Subtotal</p>
                                    <p className='font-extrabold'>${cost}.00</p>
                                </div>

                                <span className='h-px bg-[#e5e5e5] w-full absolute'></span>

                                <div className='flex items-center justify-between pl-10 pr-24 py-4 text-lg mt-0 430:pr-10'>
                                    <p className='font-extrabold'>Total</p>
                                    <p className='font-extrabold text-orange'>${cost}.00</p>
                                </div>


                                <div className='bg-greyBackground rounded pt-8 mt-8 pb-4'>
                                    <p className='text-sm text-[#616161] bg-white rounded mx-5 py-4 px-4 leading-6'>Sorry, it seems that there are no available payment methods for your state. Please contact us if you require assistance or wish to make alternate arrangements.</p>
                                    <p className='text-sm text-[#616161] leading-6 mx-5 mt-4'>Your personal data will be used to process your order, support your experience throughout this website, and for other purposes described in our <span className='text-orange'>privacy policy.</span></p>
                                    <button className="bg-darkBlueBackground 650:w-[90%] rounded py-4 px-8 font-bold text-sm text-white flex justify-center m-auto my-6 hover:bg-orange ease-in-out duration-300">PLACE ORDER</button>
                                </div>
                            </div>
                        </div>
                    </div>
                
                :   <section className='pt-24 mb-80 flex ml-[15%] items-center 650:mx-[5%]'>
                        <p className='text-lg text-greyText mr-10 font-NunitoSans'>Your cart is currently empty.</p>
                        <Link href='/Shop/Shop/Page1'><button className="bg-darkBlueBackground font-semibold text-sm text-white rounded py-3.5 px-7 hover:bg-orange ease-in-out duration-300">RETURN TO SHOP</button></Link>
                    </section>
                }
                
            </main>

            <Footer />
        </div>
    )
}