import Head from "next/head"
import Image from "next/image"
import { useEffect } from "react"

import HeaderSecond from '../../components/HeaderSecond'
import Footer from "../../components/Footer"


export default function Checkout() {
    return(
        <div>
            <Head>
                <title>ZikZag | Checkout</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../"/>
            </Head>

            <HeaderSecond />

            <main>
                <section className="bg-singleLayoutsStandardBackground bg-cover bg-no-repeat text-center text-white">
                    <h1 className="font-Amiri text-6xl pt-60 mb-6">Checkout</h1>
                    <p className="font-semibold text-sm pb-48 z-10"><span className="opacity-50">HOME &gt; </span> CHECKOUT</p>
                </section>


                {7 == 7 
                ?   <div className='mt-20 mb-40 mx-[19%]'>
                        
                    </div>
            
                :   <section className='pt-24 mb-80 flex ml-96 items-center'>
                        <p className='text-lg text-greyText mr-10 font-NunitoSans'>Your cart is currently empty.</p>
                        <button className="bg-darkBlueBackground font-semibold text-sm text-white rounded py-3.5 px-7">RETURN TO SHOP</button>
                    </section>
                }
            </main>

            <Footer />
        </div>
    )
}