import Head from 'next/head'

import HeaderAbout from '../components/HeaderAbout'
import Footer from '../components/Footer'

import AboutNotice from '../components/About/01AboutNotice'
import AboutLanding from '../components/About/02AboutLanding'
import Strategy from '../components/About/03Strategy'
import SwiperAbout from '../components/About/04SwiperAbout'
import Testimonial from '../components/Home/09Testimonial'


export default function About() {
    return (
        <div>
            <Head>
                <title>ZikZag | About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../"/>
            </Head>

            <HeaderAbout />

            <main>
                <AboutNotice />

                <AboutLanding />

                <Strategy />

                <SwiperAbout />

                <Testimonial />
            </main>

            <Footer />
        </div>
    )
}