import Head from "next/head"
import Image from "next/image"

import HeaderSecond from '../components/HeaderSecond'
import Footer from "../components/Footer"

import ContactHome03 from '../components/Home03/05Contact'

import background from '../public/assets/Contacts/background_form.jpg'
import letter1 from '../public/assets/Contacts/letter_1.png'
import letter2 from '../public/assets/Contacts/letter_2.png'
import letter3 from '../public/assets/Contacts/letter_3.png'


export default function Contacts() {
    return(
        <div class='font-NunitoSans'>
            <Head>
                <title>ZikZag | Contacts</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../"/>
            </Head>

            <HeaderSecond />

            <main>
                <section className="bg-contactBackground bg-no-repeat text-center text-white -mb-32">
                    <h1 className="font-Amiri text-6xl pt-60 mb-6">Contacts</h1>
                    <p className="font-semibold text-sm pb-48 z-10"><span className="opacity-50">HOME &gt;</span> CONTACTS</p>
                </section>

                <ContactHome03 />

                <section className='mb-14 relative mt-64'>
                    <div className='rounded-2xl bg-darkBlueBackground text-white w-[62%] px-14 py-14 absolute left-[50%] translate-x-[-50%] -top-48'>
                        <p className='font-Amiri text-[36px]'>Drop Us a Line</p>
                        <p className='text-sm mb-7'>Your email address will not be published. Required fields are marked *</p>

                        <form className='flex flex-col'>
                            <div className='flex justify-between'>
                                <input type='text' placeholder='Your Name*' className='bg-[#22303e] px-4 py-2.5 rounded placeholder:text-white outline-none w-[49%]'></input>

                                <input type='text' placeholder='Your Email*' className='bg-[#22303e] px-4 py-2.5 rounded placeholder:text-white outline-none w-[49%]'></input>
                            </div>

                            <input type='text' placeholder='Website' className='bg-[#22303e] px-4 py-2.5 rounded mt-5 placeholder:text-white outline-none'></input>

                            <textarea placeholder='Your Message...' className='bg-[#22303e] pt-4 h-32 px-4 py-2.5 rounded mt-5 placeholder:text-white outline-none'></textarea>
                        </form>

                        <button className="bg-orange font-semibold text-sm px-7 py-3.5 rounded mt-5">GET IN TOUCH</button>
                    </div>

                    <Image src={background} alt='arrière-plan' />
                    <Image src={letter1} alt='dessin de lettre' className='absolute top-20 left-20' />
                    <Image src={letter2} alt='dessin de lettre' className='absolute top-80 left-40' />
                    <Image src={letter3} alt='dessin de lettre' className='absolute right-32 top-52' />
                </section>
            </main>

            <Footer />
        </div>
    )
}