import Head from 'next/head'

import HeaderHome05 from '../components/Home05/HeaderHome05';
import Footer from '../components/Footer';
import BackToTop from '../components/BackToTop';
import WidgetTheme from '../components/WidgetTheme'

import LandingHome05 from '../components/Home05/01Landing';
import WhatOfferHome05 from '../components/Home05/02WhatOffer';
import BenefitsHome05 from '../components/Home05/03Benefits';
import OfferHome05 from '../components/Home05/04Offer';
import TestimonialHome05 from '../components/Home05/05Testimonial';
import DivisionHome05 from '../components/Home05/06Division';
import PopularHome05 from '../components/Home05/07Popular';

export default function Home05() {
    return(
        <div className='font-NunitoSans'>
            <Head>
                <title>ZikZag | Home 5</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../" />
            </Head>

            <HeaderHome05 />
            
            <main>
                <LandingHome05 />

                <WhatOfferHome05 />

                <BenefitsHome05 />

                <OfferHome05 />

                <TestimonialHome05 />

                <DivisionHome05 />

                <PopularHome05 />
            </main>

            <WidgetTheme />

            <BackToTop />

            <Footer />
        </div>
    )
}