import Head from "next/head"
import Image from "next/image"

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTwitter, faFacebookF, faPinterestP, faLinkedinIn, faInstagram } from '@fortawesome/free-brands-svg-icons'
import { faHeart } from "@fortawesome/free-solid-svg-icons"

// Swiper
import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation } from 'swiper';
import 'swiper/css';
import 'swiper/css/navigation';

import HeaderSecond from '../../components/HeaderSecond'
import Footer from "../../components/Footer"

import background from '../../public/assets/PORTFOLIO/Single/first.jpg'
import slide1 from '../../public/assets/PORTFOLIO/Single/slide_1.jpg'
import slide2 from '../../public/assets/PORTFOLIO/Single/slide_2.jpg'
import slide3 from '../../public/assets/PORTFOLIO/Single/slide_3.jpg'

import arrow  from '../../public/assets/Home02/offer_arrow.png'

import card1  from '../../public/assets/PORTFOLIO/Single/card_1.jpg'
import card2  from '../../public/assets/PORTFOLIO/Single/card_2.jpg'
import card3  from '../../public/assets/PORTFOLIO/Single/card_3.jpg'

import face1  from '../../public/assets/BLOG/BlogSingle/Standard/comment_1.jpeg'
import face2  from '../../public/assets/BLOG/BlogSingle/Standard/comment_2.jpeg'


export default function TwoColumns() {
    return(
        <div class='font-NunitoSans'>
            <Head>
                <title>ZikZag | Portfolio Single</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../"/>
            </Head>

            <HeaderSecond />

            <main>
                <section className="bg-singlePortfolioStandardBackground bg-no-repeat text-center text-white">
                    <h1 className="font-Amiri text-6xl pt-60 mb-6">Portfolio Single</h1>
                    <p className="font-semibold text-sm pb-48 z-10"><span className="opacity-50">HOME &gt; PORTFOLIO &gt; </span> BUSINESS PLANNING</p>
                </section>

                <div className='mx-[19%] mt-24 mb-40 leading-7 text-greyText'>
                    <Image src={background} alt='fiche de statistiques' className='rounded-xl' />


                    <h2 className='font-Amiri text-slightGrey text-5xl mt-10'>Business Planning</h2>
                    <div className='rounded-xl bg-darkBlueBackground px-16 py-9 my-8 flex justify-between'>
                        <div className='text-[#dddfe1]'>
                            <div className='flex items-center relative right-4'>
                                <span className='text-orange font-bold text-3xl relative bottom-[10px] mr-2'>.</span>
                                <p className='text-white font-semibold text-sm'>CLIENT</p>
                            </div>
                            <p className='my-1'>WebGeniusLab -</p>
                            <p>Creative Agency</p>
                        </div>

                        <div className='text-[#dddfe1]'>
                            <div className='flex items-center relative right-4'>
                                <span className='text-orange font-bold text-3xl relative bottom-[10px] mr-2'>.</span>
                                <p className='text-white font-semibold text-sm'>TEAM</p>
                            </div>
                            <p className='my-1'>Kate Chee - Planning</p>
                            <p className='mb-1'>Denis Ford -</p>
                            <p>Marketing Agency</p>
                        </div>

                        <div className='text-[#dddfe1]'>
                            <div className='flex items-center relative right-4'>
                                <span className='text-orange font-bold text-3xl relative bottom-[10px] mr-2'>.</span>
                                <p className='text-white font-semibold text-sm'>SERVICES</p>
                            </div>
                            <p className='my-1'>Finantial Counsulting,</p>
                            <p>Planning & Marketing</p>
                        </div>

                        <div className='text-[#dddfe1] mr-14'>
                            <div className='flex items-center relative right-4'>
                                <span className='text-orange font-bold text-3xl relative bottom-[10px] mr-2'>.</span>
                                <p className='text-white font-semibold text-sm'>CATEGORY</p>
                            </div>
                            <p className='my-1'>Marketing</p>
                        </div>
                    </div>

                    <div className='mb-6'>
                        <p className='float-left font-Amiri text-3xl text-orange bg-white px-3 pb-0.5 pt-1.5 rounded shadow-[5px_4px_13px_0_rgb(145,145,145,0.3)] mt-2 mr-4'>C</p>
                        <p>ybercrime is a threat to all the organizations, but when we take in consideration the financial market the level of menace increases exponentially. Today banks and other financial organizations face the need of providing the best possible services in the best possible way and reachable by everyone everywhere. We are increases exponentially. Today banks and other financial organizations face the need of providing the best possible services in the best possible way and reachable by everyone everywhere. We are watching to a spread of different products and services being available through the use. By 2030—little more than a decade from now—the <span className='text-orange underline'>global economy will likely be in the midst</span> of a major transformation.</p>
                    </div>
                    <p className='mb-10'>Companies and investors grapple with changing conditions constantly, but our research points to an unusual level of volatility in the decades ahead. To understand why, we look at the three major forces that will shape the 2020s: demographics, automation and inequality. These forces are already in motion and set to collide.</p>
                
                    <div className='flex justify-between'>
                        <Image src={slide1} alt='feuille de statistique' className='w-[31.5%] rounded-lg' />
                        <Image src={slide2} alt='feuille de statistique' className='w-[31.5%] rounded-lg'/>
                        <Image src={slide3} alt='feuille de statistique' className='w-[31.5%] rounded-lg' />
                    </div>


                    <h2 className='font-Amiri text-slightGrey text-4xl mt-12 mb-6'>How It Works</h2>
                    <p className='mb-6'>Companies and investors grapple with changing conditions constantly, but our research points to an unusual level of volatility in the decades ahead. To understand why, we look at the three major forces that will shape the 2020s: demographics, automation and inequality. These forces are already in motion and set to collide. Secondly, given those growth platforms, what is the brand portfolio, business portfolio that I’ll use to address them?</p>
                    <p className='mb-6'>We’re seeing an extreme rise in profitable growth from the clients that we’re supporting to reset their marketing model. But that isn’t straightforward. So actually, areas four and five are enablers. Four, what’s the data and technology strategy and the roadmap to implement that? The leaders are owning their own data, refreshing it constantly and, more importantly, using it to inform the business decisions. And they’re making the technology that underpins that a priority.</p>

                    <div className='-mx-8'>
                        <Swiper
                            modules={[Navigation]}
                            navigation
                            loop
                            speed={300}
                        >
                            <SwiperSlide>
                                <div className='rounded-lg mx-8 bg-white rounded-lg text-center m-auto my-5 shadow-[6px_5px_20px_0px_rgb(0,0,0,0.12)] max-xl:w-[850px] 850:w-10/12 testimonialSlide'>
                                    <svg viewBox="0 0 62.4 44.8" className='w-16 m-auto pt-14 pb-6'>
                                    <path style={{ fill: '#ff4a17' }} class="st0" d="M40.8,30.6c-0.9,2.3-1.7,3.9-0.9,6.5c0.7,2.3,2.5,3.9,4.5,5.2c3.7,2.4,8.7,3.6,12.6,0.9
                                    c3.8-2.5,5.8-7.3,4.4-11.7c-0.4-1.3-1.2-2.4-2.2-3.2c-2.1-3.2-6.1-4.5-9.9-4.3c-2.2,0.1-4.5,0.8-6.2,2.4c-0.6,0.6-1.1,1.2-1.6,2
                                    c-0.2,0.4-0.6,1.4-0.8,2C40.7,30.7,40.6,31.3,40.8,30.6z"></path>
                                    <path style={{ fill: '#ff4a17' }} class="st0" d="M10,41.2c4.6,3.3,12.4,4.1,15.9-1.2c1-1.5,1.5-3.1,1.6-4.6c0.6-3-0.5-6-2.8-8c-0.5-0.7-1.1-1.3-1.6-2
                                    c-1.8-2-4.9-2.2-7.2-1c-2.6,0-5.2,0.7-7.3,2.7C4.1,31.2,5.5,37.9,10,41.2z"></path>
                                    <path class="st1" d="M42,36.2c-7.2-11.4,14.9-17.4,18.7-4.6c1.7,5.8-2.8,11.2-8.6,11.6c-3.9,0.2-7.6-1.4-10.5-4.1
                                    C29,27.4,38.5,10.5,48.7,1.3c0.7-0.7-0.3-1.7-1.1-1.1C39.2,7.9,31.1,19.6,35,31.5c2.8,8.4,12.2,16.1,21.3,12
                                    c9.3-4.1,7.1-16.5-1.4-20.1c-8.5-3.5-20.1,4-14.3,13.4C41.2,37.8,42.5,37,42,36.2L42,36.2z"></path>
                                    <path class="st1" d="M8,36.2c-7.2-11.4,14.9-17.4,18.7-4.6c1.7,5.8-2.8,11.2-8.6,11.6c-3.9,0.2-7.6-1.4-10.5-4.1
                                    C-5,27.4,4.5,10.5,14.7,1.3c0.7-0.7-0.3-1.7-1.1-1.1C5.2,7.9-2.9,19.6,1,31.5c2.8,8.4,12.2,16.1,21.3,12
                                    c9.3-4.1,7.1-16.5-1.4-20.1c-8.5-3.5-20.1,4-14.3,13.4C7.2,37.8,8.5,37,8,36.2L8,36.2z"></path>
                                    </svg>

                                    <p className='text-[#61616b] text-[22px] font-light mb-10 leading-10'>“Working with ZikZag is always an absolute joy, both personally and<br></br>professionally. Tommy is an amazing speaker; her experience, expertise and<br></br>genuine passion for what she does is obvious in every word he says.”</p>
                                    <p className='font-Amiri text-3xl text-slightGrey mb-2'>Emmy Barton</p>
                                    <p className='font-semibold text-sm text-[#989898] pb-14'>CLIENT OF COMPAGNY</p>
                                </div>
                            </SwiperSlide>

                            <SwiperSlide>
                                <div className='rounded-lg mx-8 bg-white rounded-lg text-center my-5 m-auto shadow-[6px_5px_20px_0px_rgb(0,0,0,0.12)] max-xl:w-[850px] 850:w-10/12 testimonialSlide'>
                                    <svg viewBox="0 0 62.4 44.8" className='w-16 m-auto pt-14 pb-6'>
                                    <path style={{ fill: '#ff4a17' }} class="st0" d="M40.8,30.6c-0.9,2.3-1.7,3.9-0.9,6.5c0.7,2.3,2.5,3.9,4.5,5.2c3.7,2.4,8.7,3.6,12.6,0.9
                                    c3.8-2.5,5.8-7.3,4.4-11.7c-0.4-1.3-1.2-2.4-2.2-3.2c-2.1-3.2-6.1-4.5-9.9-4.3c-2.2,0.1-4.5,0.8-6.2,2.4c-0.6,0.6-1.1,1.2-1.6,2
                                    c-0.2,0.4-0.6,1.4-0.8,2C40.7,30.7,40.6,31.3,40.8,30.6z"></path>
                                    <path style={{ fill: '#ff4a17' }} class="st0" d="M10,41.2c4.6,3.3,12.4,4.1,15.9-1.2c1-1.5,1.5-3.1,1.6-4.6c0.6-3-0.5-6-2.8-8c-0.5-0.7-1.1-1.3-1.6-2
                                    c-1.8-2-4.9-2.2-7.2-1c-2.6,0-5.2,0.7-7.3,2.7C4.1,31.2,5.5,37.9,10,41.2z"></path>
                                    <path class="st1" d="M42,36.2c-7.2-11.4,14.9-17.4,18.7-4.6c1.7,5.8-2.8,11.2-8.6,11.6c-3.9,0.2-7.6-1.4-10.5-4.1
                                    C29,27.4,38.5,10.5,48.7,1.3c0.7-0.7-0.3-1.7-1.1-1.1C39.2,7.9,31.1,19.6,35,31.5c2.8,8.4,12.2,16.1,21.3,12
                                    c9.3-4.1,7.1-16.5-1.4-20.1c-8.5-3.5-20.1,4-14.3,13.4C41.2,37.8,42.5,37,42,36.2L42,36.2z"></path>
                                    <path class="st1" d="M8,36.2c-7.2-11.4,14.9-17.4,18.7-4.6c1.7,5.8-2.8,11.2-8.6,11.6c-3.9,0.2-7.6-1.4-10.5-4.1
                                    C-5,27.4,4.5,10.5,14.7,1.3c0.7-0.7-0.3-1.7-1.1-1.1C5.2,7.9-2.9,19.6,1,31.5c2.8,8.4,12.2,16.1,21.3,12
                                    c9.3-4.1,7.1-16.5-1.4-20.1c-8.5-3.5-20.1,4-14.3,13.4C7.2,37.8,8.5,37,8,36.2L8,36.2z"></path>
                                    </svg>
                                    
                                    <p className='text-greyText text-[22px] font-light mb-10'>“Choosing online studies was the best way to do it - the internet is fast, cheap &<br></br>popular and it&apos;s easy to communicate in social media with native speakers.”</p>
                                    <p className='font-Amiri text-3xl text-slightGrey mb-2'>Tina Johanson</p>
                                    <p className='font-semibold text-sm text-[#989898] pb-14'>UI DESIGNER</p>
                                </div>
                            </SwiperSlide>
                        </Swiper>
                    </div>


                    <h2 className='font-Amiri text-slightGrey text-4xl mt-12 mb-6'>Summary Results</h2>
                    <p className='leading-8 mb-10'>Consumer products marketing has experienced a profound change over the last 5 to 10 years, from a world dominated by large global brands and established TV and big-box retail models to a world that’s quickly much more complex, with a proliferation of brands, channels and marketing tools. <span className='text-slightGrey font-bold'>Technology’s disrupted the industry in three ways.</span> Firstly, it’s disrupted the way consumers engage with brands. In the UK and the US now, over 60% of consumers discover brands. There are five areas that we encourage CMOs to look at. The first is, what are my future-back platforms that will lead growth for the next 5 to 10 years? Taking today’s profit pools and forecasting them present forward just won’t capture the level of disruption that’s impacting these industries.</p>
                
                    <div className='flex items-center'>
                        <p className='text-slightGrey font-bold text-sm mr-8'>SHARE ARTICLE:</p>

                        <div className='flex items-center mr-auto'>
                            <div className='mr-2.5 bg-[#1da1f2] p-2 rounded-full hover:-translate-y-0.5 ease-in-out duration-500'><FontAwesomeIcon icon={faTwitter} className='w-3.5 text-white' /></div>
                            <div className='mr-2.5 bg-[#3b5998] py-1.5 px-2 rounded-full hover:-translate-y-0.5 ease-in-out duration-500'><FontAwesomeIcon icon={faFacebookF} className='w-2.5 text-white' /></div>
                            <div className='mr-2.5 bg-[#e40000] py-1.5 px-2 rounded-full hover:-translate-y-0.5 ease-in-out duration-500'><FontAwesomeIcon icon={faPinterestP} className='w-3 text-white' /></div>
                            <div className='mr-2.5 bg-[#007bb5] p-2 rounded-full hover:-translate-y-0.5 ease-in-out duration-500'><FontAwesomeIcon icon={faLinkedinIn} className='w-3 text-white' /></div>
                        </div>

                        <p className='bg-greyBackground rounded py-1.5 px-2.5 text-xs font-semibold'>MARKETING</p>
                        <p className='bg-greyBackground rounded py-1.5 px-2.5 text-xs font-semibold ml-2.5'>STRATEGY</p>
                        <p className='bg-greyBackground rounded py-1.5 px-2.5 text-xs font-semibold ml-2.5'>TRADE</p>
                        <div className='flex items-center rounded bg-darkBlueBackground px-2.5 text-white ml-4'>
                            <FontAwesomeIcon icon={faHeart} className='w-3 mr-1.5' />
                            <p className='font-semibold'>10</p>
                        </div>
                    </div>
                        
                    <span className='w-[63%] bg-[#e5e5e5] h-px absolute mt-8'></span>


                    <div className='flex text-white justify-center h-36 mb-28 mt-16 relative max-xl:flex-col max-xl:top-0 650:w-full'>
                        <div className='relative flex items-center bg-darkBlueBackground rounded-l-lg group max-xl:rounded-lg'>
                            <span className='absolute left-12 w-12 h-12 rounded border-white border border-solid opacity-20 group-hover:opacity-40 group-hover:-translate-x-7 ease-in-out duration-500 max-xl:right-56'></span>
                            <div className='ml-6 mr-10 rotate-180 650:px-16'><Image src={arrow} alt='icone de fleche' className=' min-w-[50px]' /></div>
                            <div className='mr-80'>
                                <p className='font-bold leading-7 mb-3'>Customer Strategy</p>
                                <p className='text-[#afbdc0] text-sm font-bold'>FEBRUARY 21, 2020</p>
                            </div>
                        </div>

                        <div className='relative flex items-center bg-orange rounded-r-lg group max-xl:rounded-lg'>
                            <div className='ml-80'>
                                <p className='font-bold leading-7 mb-3'>Partnership system</p>
                                <p className='text-[#afbdc0] text-sm font-bold'>FEBRUARY 21, 2020</p>
                            </div>
                            <span className='absolute right-14 w-12 h-12 rounded border-white border border-solid opacity-20 group-hover:opacity-40 group-hover:translate-x-7 ease-in-out duration-500 max-xl:right-56'></span>
                            <div className='ml-6 mr-10 650:px-16'><Image src={arrow} alt='icone de fleche' className=' min-w-[50px]' /></div>
                        </div>
                    </div>


                    <h2 className='font-Amiri text-slightGrey text-4xl mb-6'>Related Projects</h2>
                    <div className='flex justify-between mb-8'>
                        <div class='w-[31.5%] relative hover:cursor-pointer group'>
                            <Image src={card1} alt='réunion entreprise' className=' rounded-lg' />
                            <div className='text-center bg-white rounded-lg absolute -bottom-5 left-[50%] translate-x-[-50%] py-5 w-[90%] shadow-[6px_5px_16px_0px_rgb(0,0,0,0.15)] -translate-y-10 opacity-0 group-hover:translate-y-0 group-hover:opacity-100 ease-in-out duration-500'>
                                <p className='font-Amiri text-slightGrey text-3xl leading-[32px] mb-2 hover:text-orange ease-in-out duration-300'>People<br></br>Profesionnalism</p>
                                <p className='text-orange font-semibold text-sm'>_ MARKETING _ STRATEGY _</p>
                            </div>
                        </div>

                        <div class='w-[31.5%] relative hover:cursor-pointer group'>
                            <Image src={card2} alt='réunion entreprise' className=' rounded-lg' />
                            <div className='text-center bg-white rounded-lg absolute -bottom-5 left-[50%] translate-x-[-50%] py-5 w-[90%] shadow-[6px_5px_16px_0px_rgb(0,0,0,0.15)] -translate-y-10 opacity-0 group-hover:translate-y-0 group-hover:opacity-100 ease-in-out duration-500'>
                                <p className='font-Amiri text-slightGrey text-3xl leading-[32px] mb-2 hover:text-orange ease-in-out duration-300'>Corporate Finance</p>
                                <p className='text-orange font-semibold text-sm'>_ MARKETING _ STARTUP _</p>
                            </div>
                        </div>

                        <div class='w-[31.5%] relative hover:cursor-pointer group'>
                            <Image src={card3} alt='réunion entreprise' className=' rounded-lg' />
                            <div className='text-center bg-white rounded-lg absolute -bottom-5 left-[50%] translate-x-[-50%] py-5 w-[90%] shadow-[6px_5px_16px_0px_rgb(0,0,0,0.15)] -translate-y-10 opacity-0 group-hover:translate-y-0 group-hover:opacity-100 ease-in-out duration-500'>
                                <p className='font-Amiri text-slightGrey text-3xl leading-[32px] mb-2 hover:text-orange ease-in-out duration-300'>Flexibility &<br></br>Adaptability</p>
                                <p className='text-orange font-semibold text-sm'>_ FINANCE _ MARKETING _</p>
                            </div>
                        </div>
                    </div>


                    <h2 className='text-slightGrey font-Amiri text-4xl py-10'>Comments <span className='text-[#d3d3d3]'>(02)</span></h2>
                    <div>
                        <div className='flex relative mb-8'>
                            <Image src={face1} alt='portrait' className='w-[80px] h-[80px] relative top-2.5' />

                            <div className='pl-8'>
                                <p className='font-bold text-slightGrey'>David Parker</p>
                                <p className='text-sm font-semibold text-[#d3d3d3] mb-4'>FEBRUARY 24, 2020</p>
                                <p>This is a useful post for finding broken links within the website, what about links pointing outwards that are broken? I can use a free web service but wondered if this was possible.</p>
                            </div>

                            <p className='text-orange text-sm font-semibold absolute top-0 right-0'>REPLY</p>
                        </div>

                        <span className='w-[40%] bg-[#e5e5e5] h-px absolute'></span>

                        <div className='flex relative mt-16 ml-28'>
                            <Image src={face2} alt='portrait' className='w-[80px] h-[80px] relative top-2.5' />

                            <div className='pl-8'>
                                <p className='font-bold text-slightGrey'>David Parker</p>
                                <p className='text-sm font-semibold text-[#d3d3d3] mb-4'>FEBRUARY 24, 2020</p>
                                <p>This is a useful post for finding broken links within the website, what about links pointing outwards that are broken? I can use a free web service but wondered if this was possible.</p>
                            </div>

                            <p className='text-orange text-sm font-semibold absolute top-0 right-0'>REPLY</p>
                        </div>
                    </div>


                    <div className='rounded-2xl px-14 py-14 mt-32 bg-white shadow-[6px_5px_30px_0px_rgb(0,0,0,0.12)] mb-48'>
                        <p className='font-Amiri text-slightGrey text-[36px]'>Leave a Reply</p>
                        <p className='text-sm mb-7'>Your email address will not be published. Required fields are marked *</p>

                        <form className='flex flex-col'>
                            <div className='flex justify-between'>
                                <input type='text' placeholder='Name *' className='bg-greyBackground px-4 py-2.5 rounded placeholder:text-greyText outline-none w-[49%]'></input>

                                <input type='text' placeholder='Your Email*' className='bg-greyBackground px-4 py-2.5 rounded placeholder:text-greyText outline-none w-[49%]'></input>
                            </div>

                            <input type='text' placeholder='Website' className='bg-greyBackground px-4 py-2.5 rounded mt-5 placeholder:text-greyText outline-none'></input>

                            <textarea placeholder='Your Comment...' className='bg-greyBackground pt-4 h-32 px-4 py-2.5 rounded mt-5 placeholder:text-greyText outline-none'></textarea>
                        
                            <div className='flex'>
                                <input type='checkbox' className='mt-4 self-start'></input>
                                <p className='ml-3 relative top-1.5'>Save my name, email, and website in this browser for the next time I comment.</p>
                            </div>
                        </form>

                        <button className="bg-orange text-white font-semibold text-sm px-7 py-3.5 rounded mt-5 hover:bg-darkBlueBackground ease-in-out duration-500">POST COMMENT</button>
                    </div>
                </div>
            </main>

            <Footer />
        </div>
    )
}