import Head from "next/head"
import Image from "next/image";

// Swiper
import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation, Autoplay, EffectFade } from 'swiper';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/autoplay';
import 'swiper/css/effect-fade';

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faUser, faComment } from "@fortawesome/free-regular-svg-icons"
import { faHeart, faEye } from "@fortawesome/free-solid-svg-icons"

import HeaderSecond from '../../../components/HeaderSecond'
import Footer from "../../../components/Footer"
import StandardArticle from "../../../components/BLOG/StandardArticle"
import AsideArticle from "../../../components/BLOG/AsideArticle"

import slide1 from '../../../public/assets/BLOG/BlogSingle/Gallery/slide_1.jpg'
import slide2 from '../../../public/assets/BLOG/BlogSingle/Gallery/slide_2.jpg'
import slide3 from '../../../public/assets/BLOG/BlogSingle/Gallery/slide_3.jpg'


export default function Gallery() {
    return(
        <div class='font-NunitoSans'>
            <Head>
                <title>ZikZag | Blog Gallery</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../"/>
            </Head>

            <HeaderSecond />

            <main>
                <section className='bg-videoStandardBackground bg-cover bg-top bg-no-repeat pt-80 px-[19%] text-white 430-850:px-[5%] 430:px-[5%]'>
                    <div className='bg-orange flex flex-col items-center justify-center rounded w-[60px] py-0.5 mb-7'>
                        <p className='font-Amiri text-[26px]'>24</p>
                        <p className='text-xs font-semibold relative bottom-2'>FEB</p>
                    </div>

                    <p className='font-semibold mb-6'>ANALYSIS _ NEWS</p>
                    <h1 className='font-Amiri text-6xl 650:text-5xl'>When Sustainability Requires Change</h1>

                    <span className='w-[62%] h-px bg-[#6e6f6f] absolute mt-10 850:w-[90%]'></span>

                    <div className='flex mt-16 pb-8 650-850:min-w-[470px] 650:min-w-[300px] 650:flex-col'>
                        <div className='flex items-center mr-8 650:mb-3'>
                            <FontAwesomeIcon icon={faUser} className='w-3 mr-2' />
                            <p className='font-semibold'>By Kate Black</p>
                        </div>

                        <div className='flex items-center mr-auto 650:mb-3'>
                            <FontAwesomeIcon icon={faComment} className='w-3 mr-2' />
                            <p className='font-semibold'>2 Comments</p>
                        </div>

                        <div className='flex items-center rounded bg-darkBlueBackground py-0.5 px-2.5 650:mb-3 650:w-[60px]'>
                            <FontAwesomeIcon icon={faHeart} className='w-3 mr-1' />
                            <p className='font-semibold'>11</p>
                        </div>

                        <div className='flex items-center rounded bg-darkBlueBackground py-0.5 px-2.5 ml-2 650:mb-3 650:ml-0 650:w-[60px]'>
                            <FontAwesomeIcon icon={faEye} className='w-3 mr-1' />
                            <p className='font-semibold'>139</p>
                        </div>
                    </div>
                </section>


                <div className='w-[62%] m-auto mt-12 flex justify-between min-w-[1180px] max-xl:flex-col max-xl:items-center max-xl:pb-40 max-xl:min-w-[300px]'>
                    <div className='w-[74%] max-xl:w-full'>
                        <div className='mb-10 rounded-xl overflow-hidden'>
                            <Swiper
                                modules={[Navigation, Autoplay, EffectFade]}
                                navigation={{
                                    nextEl: '.GalleryNavigationNext',
                                    prevEl: '.GalleryNavigationPrev'
                                }}
                                effect="fade"
                                speed={1000}
                                autoplay={{
                                    delay: 5000
                                }}
                                loop
                            >
                                <SwiperSlide className="relative group">
                                    <Image src={slide1} alt="clavier d'ordinateur" />
                                    <div className='absolute bottom-10 left-10 w-32'>
                                        <button className='GalleryNavigationPrev group-hover:-translate-x-1.5 ease-in-out duration-500 w-14 h-0.5 bg-white right-20 absolute'><span className='w-3 h-0.5 bg-white -rotate-45 absolute -left-0.5 bottom-1'></span><span className='w-3 h-0.5 bg-white rotate-45 absolute -left-0.5 top-1'></span></button>
                                        <button className='GalleryNavigationNext group-hover:translate-x-1.5 ease-in-out duration-500 w-14 h-0.5 bg-white absolute left-20'><span className='w-3 h-0.5 bg-white rotate-45 absolute -right-0.5 bottom-1'></span><span className='w-3 h-0.5 bg-white -rotate-45 absolute -right-0.5 top-1'></span></button>
                                    </div>
                                </SwiperSlide>

                                <SwiperSlide className="relative group">
                                    <Image src={slide2} alt="réunion entreprise" />
                                    <div className='absolute bottom-10 left-10 w-32'>
                                        <button className='GalleryNavigationPrev group-hover:-translate-x-1.5 ease-in-out duration-500 w-14 h-0.5 bg-white right-20 absolute'><span className='w-3 h-0.5 bg-white -rotate-45 absolute -left-0.5 bottom-1'></span><span className='w-3 h-0.5 bg-white rotate-45 absolute -left-0.5 top-1'></span></button>
                                        <button className='GalleryNavigationNext group-hover:translate-x-1.5 ease-in-out duration-500 w-14 h-0.5 bg-white absolute left-20'><span className='w-3 h-0.5 bg-white rotate-45 absolute -right-0.5 bottom-1'></span><span className='w-3 h-0.5 bg-white -rotate-45 absolute -right-0.5 top-1'></span></button>
                                    </div>
                                </SwiperSlide>

                                <SwiperSlide className="relative group">
                                    <Image src={slide3} alt="femme travaillant sur un ordinateur" />
                                    <div className='absolute bottom-10 left-10 w-32'>
                                        <button className='GalleryNavigationPrev group-hover:-translate-x-1.5 ease-in-out duration-500 w-14 h-0.5 bg-white right-20 absolute'><span className='w-3 h-0.5 bg-white -rotate-45 absolute -left-0.5 bottom-1'></span><span className='w-3 h-0.5 bg-white rotate-45 absolute -left-0.5 top-1'></span></button>
                                        <button className='GalleryNavigationNext group-hover:translate-x-1.5 ease-in-out duration-500 w-14 h-0.5 bg-white absolute left-20'><span className='w-3 h-0.5 bg-white rotate-45 absolute -right-0.5 bottom-1'></span><span className='w-3 h-0.5 bg-white -rotate-45 absolute -right-0.5 top-1'></span></button>
                                    </div>
                                </SwiperSlide>
                            </Swiper>
                        </div>

                        <StandardArticle />
                    </div>

                    <AsideArticle />
                </div>
            </main>

            <Footer />
        </div>
    )
}