import Head from "next/head"
import Image from "next/image";

// Swiper
import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation, Autoplay, EffectFade } from 'swiper';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/autoplay';
import 'swiper/css/effect-fade';

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faUser, faComment } from "@fortawesome/free-regular-svg-icons"
import { faHeart, faEye } from "@fortawesome/free-solid-svg-icons"

import HeaderSecond from '../../../components/HeaderSecond'
import Footer from "../../../components/Footer"
import StandardArticle from "../../../components/BLOG/StandardArticle"
import AsideArticle from "../../../components/BLOG/AsideArticle"

import slide1 from '../../../public/assets/BLOG/BlogSingle/Gallery/slide_1.jpg'
import slide2 from '../../../public/assets/BLOG/BlogSingle/Gallery/slide_2.jpg'
import slide3 from '../../../public/assets/BLOG/BlogSingle/Gallery/slide_3.jpg'


export default function Gallery() {
    return(
        <div class='font-NunitoSans'>
            <Head>
                <title>ZikZag | Blog Gallery</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../"/>
            </Head>

            <HeaderSecond />

            <main>
                <section className='bg-videoStandardBackground bg-top bg-no-repeat pt-80 px-[19%] text-white'>
                    <div className='bg-orange flex flex-col items-center justify-center rounded w-[60px] py-0.5 mb-7'>
                        <p className='font-Amiri text-[26px]'>24</p>
                        <p className='text-xs font-semibold relative bottom-2'>FEB</p>
                    </div>

                    <p className='font-semibold mb-6'>ANALYSIS _ NEWS</p>
                    <h1 className='font-Amiri text-6xl'>When Sustainability Requires Change</h1>

                    <span className='w-[62%] h-px bg-[#6e6f6f] absolute mt-10'></span>

                    <div className='flex mt-16 pb-8'>
                        <div className='flex items-center mr-8'>
                            <FontAwesomeIcon icon={faUser} className='w-3 mr-2' />
                            <p className='font-semibold'>By Kate Black</p>
                        </div>

                        <div className='flex items-center mr-auto'>
                            <FontAwesomeIcon icon={faComment} className='w-3 mr-2' />
                            <p className='font-semibold'>2 Comments</p>
                        </div>

                        <div className='flex items-center rounded bg-darkBlueBackground py-0.5 px-2.5'>
                            <FontAwesomeIcon icon={faHeart} className='w-3 mr-1' />
                            <p className='font-semibold'>11</p>
                        </div>

                        <div className='flex items-center rounded bg-darkBlueBackground py-0.5 px-2.5 ml-2'>
                            <FontAwesomeIcon icon={faEye} className='w-3 mr-1' />
                            <p className='font-semibold'>139</p>
                        </div>
                    </div>
                </section>


                <div className='mx-[19%] mt-12 flex justify-between'>
                    <div className='w-[74%]'>
                        <div className='mb-10 rounded-xl overflow-hidden'>
                            <Swiper
                                modules={[Navigation, Autoplay, EffectFade]}
                                navigation
                                effect="fade"
                                speed={1000}
                                autoplay={{
                                    delay: 5000
                                }}
                                loop
                            >
                                <SwiperSlide>
                                    <Image src={slide1} alt="clavier d'ordinateur" />
                                </SwiperSlide>

                                <SwiperSlide>
                                    <Image src={slide2} alt="réunion entreprise" />
                                </SwiperSlide>

                                <SwiperSlide>
                                    <Image src={slide3} alt="femme travaillant sur un ordinateur" />
                                </SwiperSlide>
                            </Swiper>
                        </div>

                        <StandardArticle />
                    </div>

                    <AsideArticle />
                </div>
            </main>

            <Footer />
        </div>
    )
}