import Head from "next/head"

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import { faUser, faComment } from "@fortawesome/free-regular-svg-icons"
import { faHeart, faEye } from "@fortawesome/free-solid-svg-icons"

import HeaderSecond from '../../../components/HeaderSecond'
import Footer from "../../../components/Footer"
import StandardArticle from "../../../components/BLOG/StandardArticle"
import AsideArticle from "../../../components/BLOG/AsideArticle"


export default function Music() {
    return(
        <div class='font-NunitoSans'>
            <Head>
                <title>ZikZag | Blog Music</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="../"/>
            </Head>

            <HeaderSecond />

            <main>
                <section className='bg-musicStandardBackground bg-cover bg-top bg-no-repeat pt-80 px-[19%] text-white 430-850:px-[5%] 430:px-[5%]'>
                    <div className='bg-orange flex flex-col items-center justify-center rounded w-[60px] py-0.5 mb-7'>
                        <p className='font-Amiri text-[26px]'>24</p>
                        <p className='text-xs font-semibold relative bottom-2'>FEB</p>
                    </div>

                    <p className='font-semibold mb-6'>FINANCE</p>
                    <h1 className='font-Amiri text-6xl leading-[80px]'>Getting Teamwork Right at the Top</h1>

                    <span className='w-[62%] h-px bg-[#6e6f6f] absolute mt-10 850:w-[90%]'></span>

                    <div className='flex mt-16 pb-8 650-850:min-w-[470px] 650:min-w-[300px] 650:flex-col'>
                        <div className='flex items-center mr-8 650:mb-3'>
                            <FontAwesomeIcon icon={faUser} className='w-3 mr-2' />
                            <p className='font-semibold'>By Kate Black</p>
                        </div>

                        <div className='flex items-center mr-auto 650:mb-3'>
                            <FontAwesomeIcon icon={faComment} className='w-3 mr-2' />
                            <p className='font-semibold'>2 Comments</p>
                        </div>

                        <div className='flex items-center rounded bg-darkBlueBackground py-0.5 px-2.5 650:mb-3 650:w-[60px]'>
                            <FontAwesomeIcon icon={faHeart} className='w-3 mr-1' />
                            <p className='font-semibold'>8</p>
                        </div>

                        <div className='flex items-center rounded bg-darkBlueBackground py-0.5 px-2.5 ml-2 650:ml-0 650:mb-3 650:w-[60px]'>
                            <FontAwesomeIcon icon={faEye} className='w-3 mr-1' />
                            <p className='font-semibold'>74</p>
                        </div>
                    </div>
                </section>


                <div className='w-[62%] m-auto mt-12 flex justify-between min-w-[1180px] max-xl:flex-col max-xl:items-center max-xl:pb-40 max-xl:min-w-fit'>
                    <div className='w-[74%] max-xl:w-full'>
                        <iframe width="100%" height="505" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/280437402&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe>
                        <div className='mb-10' style={{fontSize: 10, color: '#cccccc', lineBreak: 'anywhere', wordBreak: 'normal', overflow: "hidden", whiteSpace: "nowrap", textOverflow: "ellipsis", fontFamily: "Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif", fontWeight: 100}}>
                            <a href="https://soundcloud.com/shadowanthem" title="Shadow Anthem" style={{color: '#cccccc', textDecoration: 'none'}}>Shadow Anthem</a>
                            <a href="https://soundcloud.com/shadowanthem/twenty-one-pilots-heathens-prismo-remix" title="Twenty One Pilots - Heathens (Prismo Remix)" style={{color: '#cccccc', textDecoration: 'none'}}>Twenty One Pilots - Heathens (Prismo Remix)</a>
                        </div>

                        <StandardArticle />
                    </div>

                    <AsideArticle />
                </div>
            </main>

            <Footer />
        </div>
    )
}